name: Run

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker buildx build --platform=linux/amd64 -t ipfs-boot-choo .
          docker run --rm -i --platform=linux/amd64 -v ./dist:/root/dist ipfs-boot-choo | tee out.txt

      - name: Check docs
        run: |
          cidv1_1=$(cat out.txt | grep "CIDv1 =" | awk '{print $3}')
          cidv1_2=$(cat README.md | grep "CIDv1 =" | awk '{print $4}')
          cidv1_3=$(cat versions.json | jq -r .arr[-1].cid)
          [ "$cidv1_1" = "$cidv1_2" ] || exit 1
          [ "$cidv1_1" = "$cidv1_3" ] || exit 1

      - name: Zip
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
